name: Cypress Tests

on: 
  schedule:
    - cron:  '0 21 * * *'
  workflow_dispatch:
env:
  SLACK_WEBHOOK_URL: ${{ secrets.slack_webhook_url }}
  AZURE_STORAGE_KEY: ${{ secrets.azure_dev_storage_key }}
  GITHUB_TOKEN: ${{ secrets.pointr_github_token }}
concurrency:
  group: nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run test
      - name: slack report
        if: success() || failure()
        run: |
          export REPORT_HTML=cypress/results/cucumber-report.html
          export BASE_REPO_NAME=${GITHUB_REPOSITORY#*/}
          python cypress/report_to_slack.py web-bot cypress/results/cucumber-report.json